kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd
---
kind: JoinConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
discovery:
  bootstrapToken:
    token: "<token>"
    apiServerEndpoint: "control-plane.lolava.xyz:6443"
    caCertHashes:
      - "<caCertHash>"
    unsafeSkipCAVerification: false
controlPlane:
  certificateKey: "<cKey>"
