kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
kubernetesVersion: v1.30.0
controlPlaneEndpoint: "control-plane.lolava.xyz:6443"
clusterName: kubernetes
networking:
  dnsDomain: cluster.local
  podSubnet: "10.0.0.0/16"
  serviceSubnet: "10.8.0.0/16"
certificatesDir: /etc/kubernetes/pki
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: registry.k8s.io
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd
